[settings]
env_shell_expand = true

[env]
HCLOUD_TOKEN = "{{ get_env(name='HCLOUD_TOKEN', default=exec(command='pass infrastructure/pelle.io/cloud_api_token')) }}"
GITHUB_TOKEN = "{{ get_env(name='GITHUB_TOKEN', default=exec(command='pass github/pellepelster/pat/admin')) }}"

[tools]
terraform="1.15.2"

[tasks."cloud:apply"]
run = "blcks cloud apply pelle.yaml"

[tasks."cloud:plan"]
run = "blcks cloud plan pelle.yaml"

[tasks."tf:plan"]
dir = "terraform/pelle.io"
run = "terraform plan"

[tasks."tf:apply"]
dir = "terraform/pelle.io"
run = "terraform apply"

[tasks."tf:init"]
dir = "terraform/pelle.io"
run = "terraform init -upgrade"

[tasks."dev:status"]
dir = "~/git/solidblocks"
run = "./gradlew clean :solidblocks-cli:run --args=\"cloud status ${HOME}/git/infrastructure/pelle.yaml\""

[tasks."dev:maintenance"]
dir = "~/git/solidblocks"
run = "./gradlew clean :solidblocks-cli:run --args=\"cloud maintenance ${HOME}/git/infrastructure/pelle.yaml\""

[tasks."dev:apply"]
dir = "~/git/solidblocks"
run = "./gradlew clean :solidblocks-cli:run --args=\"cloud apply ${HOME}/git/infrastructure/pelle.yaml\""
